<#
Regenerates src\Weatherspell\Weather\PostalCodes.tsv, the table behind postal
code search for the countries Open-Meteo's geocoder does not index. Its
postcode search is dependable for the US, France, Spain, the Netherlands and
Belgium, patchy elsewhere in Europe and absent for Canada, the UK, Australia,
New Zealand and Ireland (probed 2026-09-12), so the exe carries those five,
the English-speaking countries a Weatherspell user is likely to type. Adding
a country is one line in $Countries, if GeoNames has its codes at town
precision and the table stays small.

Data: the GeoNames postal code dump (CC BY 4.0), one row per place per code.
For Canada and Ireland GeoNames has only the first part of a code (the
forward sortation area, the routing key); for the UK the outward code. A
code shared by several places (13 villages in IP8, 9 suburbs in Sydney 2000,
162 in one Scottish district) becomes one entry named after its most
populous place according to the GeoNames gazetteer (cities500), then a place
named like its district, then the first listed; one entry per code keeps the
results list short and the forecast is the same across a code anyway.

    powershell -NoProfile -ExecutionPolicy Bypass -File tools\Update-PostalCodes.ps1
#>
param(
    [string]$Target = (Join-Path $PSScriptRoot "..\src\Weatherspell\Weather\PostalCodes.tsv")
)

$ErrorActionPreference = "Stop"

# Country code, the name Open-Meteo's geocoder uses for it (so results from
# both sources read alike), and the length to cut codes to (0 = as is).
$Countries = @(
    @{ Code = "CA"; Name = "Canada";         Cut = 3 }
    @{ Code = "GB"; Name = "United Kingdom"; Cut = 0 }
    @{ Code = "AU"; Name = "Australia";      Cut = 0 }
    @{ Code = "NZ"; Name = "New Zealand";    Cut = 0 }
    @{ Code = "IE"; Name = "Ireland";        Cut = 0 }
)
# GeoNames names two territories differently from its own gazetteer.
$RegionFixes = @{
    "Northwest Territory" = "Northwest Territories"
    "Nunavut Territory"   = "Nunavut"
}

$work = Join-Path $env:TEMP "weatherspell-geonames"
New-Item -ItemType Directory -Force $work | Out-Null
function Fetch($name, $url) {
    $zip = Join-Path $work "$name.zip"
    Invoke-WebRequest -Uri $url -OutFile $zip
    Expand-Archive -Path $zip -DestinationPath (Join-Path $work $name) -Force
    Get-ChildItem (Join-Path $work $name) -Filter "*.txt" | Where-Object Name -ne "readme.txt" | Select-Object -First 1 -ExpandProperty FullName
}

$gazetteerPath = Fetch "cities500" "https://download.geonames.org/export/dump/cities500.zip"
$wanted = @{}
foreach ($c in $Countries) { $wanted[$c.Code] = $true }

# Gazetteer: country|lower-case name -> places (latitude, longitude, population).
$gazetteer = New-Object "System.Collections.Generic.Dictionary[string,System.Collections.Generic.List[object]]"
foreach ($line in [System.IO.File]::ReadLines($gazetteerPath)) {
    $f = $line.Split("`t")
    if ($f.Length -lt 15 -or -not $wanted.ContainsKey($f[8])) { continue }
    $key = $f[8] + "|" + $f[1].ToLowerInvariant()
    if (-not $gazetteer.ContainsKey($key)) { $gazetteer[$key] = New-Object System.Collections.Generic.List[object] }
    $gazetteer[$key].Add(@{ Lat = [double]$f[4]; Lon = [double]$f[5]; Pop = [long]$f[14] })
}

function Population($cc, $name, $lat, $lon) {
    $key = $cc + "|" + $name.ToLowerInvariant()
    if (-not $gazetteer.ContainsKey($key)) { return -1 }
    $best = -1
    foreach ($g in $gazetteer[$key]) {
        # Same name within about 30 km; a namesake across the country does not count.
        if ([math]::Abs($g.Lat - $lat) -lt 0.3 -and [math]::Abs($g.Lon - $lon) -lt 0.5 -and $g.Pop -gt $best) { $best = $g.Pop }
    }
    return $best
}

$output = New-Object System.Collections.Generic.List[string]
$output.Add("# Postal codes from GeoNames (geonames.org), licensed CC BY 4.0: one entry per code, named after its most populous place. Regenerated by tools\Update-PostalCodes.ps1 on $(Get-Date -Format yyyy-MM-dd). Columns: code, place name, region, country, latitude, longitude.")
$total = 0
foreach ($c in $Countries) {
    $path = Fetch $c.Code "https://download.geonames.org/export/zip/$($c.Code).zip"
    $groups = New-Object "System.Collections.Generic.Dictionary[string,System.Collections.Generic.List[object]]"
    foreach ($line in [System.IO.File]::ReadLines($path)) {
        $f = $line.Split("`t")
        if ($f.Length -lt 11 -or $f[0] -ne $c.Code) { continue }
        $code = ($f[1] -replace "\s", "").ToUpperInvariant()
        if ($c.Cut -gt 0 -and $code.Length -gt $c.Cut) { $code = $code.Substring(0, $c.Cut) }
        if ($code.Length -eq 0) { continue }
        $region = $f[3].Trim()
        if ($RegionFixes.ContainsKey($region)) { $region = $RegionFixes[$region] }
        if (-not $groups.ContainsKey($code)) { $groups[$code] = New-Object System.Collections.Generic.List[object] }
        $groups[$code].Add(@{
            Name = $f[2].Trim(); Region = $region; District = @($f[5].Trim(), $f[7].Trim())
            Lat = [double]$f[9]; Lon = [double]$f[10]; LatText = $f[9].Trim(); LonText = $f[10].Trim()
        })
    }
    foreach ($code in ($groups.Keys | Sort-Object)) {
        $places = $groups[$code]
        $pick = $places[0]
        if ($places.Count -gt 1) {
            $bestPop = -1
            foreach ($p in $places) {
                $pop = Population $c.Code $p.Name $p.Lat $p.Lon
                if ($pop -gt $bestPop) { $bestPop = $pop; $pick = $p }
            }
            if ($bestPop -lt 0) {
                foreach ($p in $places) { if ($p.District -contains $p.Name) { $pick = $p; break } }
            }
        }
        $output.Add(($code, $pick.Name, $pick.Region, $c.Name, $pick.LatText, $pick.LonText) -join "`t")
        $total++
    }
    Write-Host "$($c.Name): $($groups.Count) codes"
}

# UTF-8 without a BOM: Out-File would add one, and the names carry accents.
$utf8 = New-Object System.Text.UTF8Encoding $false
$full = [System.IO.Path]::GetFullPath($Target)
[System.IO.File]::WriteAllText($full, ($output -join "`n") + "`n", $utf8)
Write-Host "Wrote $total codes to $full"
